// <auto-generated />
using Cesi.IntroCS.CoreDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cesi.IntroCS.CoreDataAccess.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20190101205705_foreignkeyTest")]
    partial class foreignkeyTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cesi.IntroCS.CoreDataAccess.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Cesi.IntroCS.CoreDataAccess.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogId");

                    b.Property<string>("Content");

                    b.Property<int>("FK_Posts_Blogs_BlogId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("FK_Posts_Blogs_BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Cesi.IntroCS.CoreDataAccess.Entities.Post", b =>
                {
                    b.HasOne("Cesi.IntroCS.CoreDataAccess.Entities.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("FK_Posts_Blogs_BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
